### ISSUE TITLE
Metrics by persona

### ISSUE THREAD

**Issue by tumido** [AICoE/data-driven-development#21]
@goern suggests to have metrics organized by personas

**Comment by hemajv** [comment]
Based on the personas identified in #22, we should group our metrics accordingly

**Comment by hemajv** [comment]
Updated the metric doc [here](https://docs.google.com/document/d/1SWv29LkjKUA4rkM3V6bR6GzVWJPWMgHm-RUPH7xiPrE/edit?usp=sharing) to include a section on metric grouped by personas

**Comment by tumido** [comment]
Resolved via https://github.com/AICoE/meteor/pull/42
