### ISSUE TITLE
Define meteor personas

### ISSUE THREAD

**Issue by tumido** [AICoE/data-driven-development#22]
Identify the different personas involved in Project Meteor. These personas or roles are the different groups of users who are involved in Project Meteor and are interacting with it for different purposes.

**Comment by Shreyanand** [comment]
I guess the broad categories would be _Product owner_ and the _User_ as suggested by @goern. Are there any other major players here?

Within _Product owner_ category, we could have sub categories for Devops and Data Scientists (pipeline and model metrics). For the _User_ persona, do we mean all the user behavior metrics like number of users and completion rate?

**Comment by hemajv** [comment]
So I was thinking we could classify them as:

**Product Owner** - Project's key stakeholder i.e Marcel/Christoph who communicate the vision of the product to the team/stakeholders and ensure the feasibility of the product with respect to business objectives 

**Operations** - Primary focused on application management, application maintenance and instrumental in automation of application development processes

**Technical Architect** - Provides technical feasibility of requirements, advise on technology choices and manage the technical roadmap i.e. Team Comet members

**Users** - Users interacting with the product (who we are building the product for) and this can probably have sub categories like:

- Data Scientists - Data Scientists would be our core product user that we would be targeting i.e Team Shooting Star members  
- Generic User - These are the adjacent users who may use our product and probably make up a much smaller percentage of our target audience


Open to any suggestions/inputs on breaking this down further

**Comment by harshad16** [comment]
we should consider another set of users.
who are project managers or supervisors. They would like to view what is the efficiency or performance growth by using this tool. i.e the owner of the other projects which would like to use this tool. 

another persona, which we came across while working with odh ,is the consultant. A person who would like to present this to the actual users, i don't know what would be different from there side, but i would like thing that a user would need to configure this tool on site and etc
wdyt?

**Comment by hemajv** [comment]
@harshad16 I think **project manager** would be a good addition and as you pointed out different teams might adopt the tool for their needs. We can add that :+1: 

I am not too sure if a _consultant_ would be as relevant for us now, given that this product (being hosted as an application online) might be completely self on-boarding and not too sure if we would need this user right now, wdyt?

**Comment by harshad16** [comment]
i agree with your thoughts on this application being hosted. we can skip the consultant persona.
i think we should add a person of Team telescope: Analyst: Users who are only concern on the quality of the metrics/analysis that is done when a application is deployed or build with this application :sweat_smile:

**Comment by hemajv** [comment]
ah yes, I was thinking about that too...since Team Telescope is mainly looking into defining these metrics for different personas, I wasn't sure if we also should be considered as a separate persona :sweat_smile: but let me include it and we can further iterate on the list if required!
