### ISSUE TITLE
Spike: Identify the most active app/service/component that would benefit from monitoring

### ISSUE THREAD

**Issue by hemajv** [AICoE/data-driven-development#23]
Identify the most active app/service/component that can be used as an example for outlining the end-end monitoring workflow from setting up operation tooling, collecting and storing metrics, interacting with metrics (notebooks etc) and visualizing the metrics.

**Comment by pacospace** [comment]
- [ ] Kebechet
- [ ] Meteor
- [ ] JupyterHub
- [ ] PostgreSQL database
- [ ] pipelines with argo workflows
- [ ] pipelines with Tekton

**Comment by hemajv** [comment]
Initial doc outlining the monitoring workflow: https://docs.google.com/document/d/1xAkyLDXgAG7V_4u6NY28L93COMPzsHG7Xs69JUV8aVQ/edit?usp=sharing

**Comment by hemajv** [comment]
I think we can consider Kebechet as our example application as it would be a good use case to explore how we monitor an application consisting of multiple dependent components, monitoring data sources, etc.

thoughts @harshad16 @pacospace @xtuchyna @goern @durandom?

**Comment by goern** [comment]
https://github.com/thoth-station/kebechet/issues/546
