### ISSUE TITLE
Revisit Kebechet metrics

### ISSUE THREAD

**Issue by hemajv** [AICoE/data-driven-development#28]
Revisit and update Kebechet metrics

**Acceptance Criteria**

- [ ] Grafana dashboard
- [ ] Superset dashboard

**Comment by pacospace** [comment]
Depends-On: https://github.com/thoth-station/core/issues/322
Depends-On: https://github.com/thoth-station/thoth-application/issues/2165
Depends-On: https://github.com/thoth-station/thoth-application/issues/2149
Depends-On: https://github.com/thoth-station/thoth-application/issues/2142
