### ISSUE TITLE
grafana.md | here-link leads to an Error, Restricted Access

### ISSUE THREAD

**Issue by schwesig** [AICoE/data-driven-development#57]
**Describe the bug**
The "here"-link under Step 1 is not working/leads to a page that shows an error/permission problem. This could be confusing for starters and should maybe better link to grafana.operate-first.cloud

Location:
in
https://github.com/AICoE/data-driven-development/blob/main/data-presentation/grafana.md

under Step 1.
"We have Grafana deployed in one of the Operate First instances and it can be accessed **_here_**. You can [..]"
here --> https://console-openshift-console.apps.smaug.na.operate-first.cloud/k8s/ns/opf-monitoring/routes/grafana

**To Reproduce**
1. Go to (https://github.com/AICoE/data-driven-development/blob/main/data-presentation/grafana.md)
2. Click on "here" in Step 1. [..] We have Grafana deployed in one of the Operate First instances and it can be accessed here. You can follow the instructions for accessing and adding dashboards here.
3. See error: Restricted Access | Danger alert:Error details
routes.route.openshift.io "grafana" is forbidden: User "schwesig" cannot get resource "routes" in API group "route.openshift.io" in the namespace "opf-monitoring"

**Expected behavior**
The link should lead to a webpage where you can start with grafana on operate first; e.g. grafana.operate-first.cloud

**Screenshots**
![Trigger - Screenshot from 2021-11-22 08-03-07](https://user-images.githubusercontent.com/89909507/142866771-06d27cf8-6a7c-4fed-bbb9-e0b2449a8bba.png)
![Error - Screenshot from 2021-11-22 08-03-59](https://user-images.githubusercontent.com/89909507/142866767-199b1b6f-1042-460b-b258-b7dc2cda7aee.png)

**Additional context**
n/a

**Comment by hemajv** [comment]
Thanks for pointing this out @schwesig :+1:
