### ISSUE TITLE
Notebook for interacting with Prometheus data

### ISSUE THREAD

**Issue by hemajv** [AICoE/data-driven-development#6]
Add a notebook that provides step-step instructions on how to interact with Prometheus data.

**Acceptance Criteria:**

- [ ] Notebook in the `notebooks` folder that provides an overview of how to interact programmatically with Prometheus

**Comment by MichaelClifford** [comment]
/remove-lifecycle rotten 

@hemajv does this notebook suffice to close this issue?  

https://github.com/aicoe-aiops/time-series/blob/master/notebooks/ts-1-fetching-metrics.ipynb ?
