### ISSUE TITLE
Visualizing metrics page not found in data-driven-development/examples/kebechet/

### ISSUE THREAD

**Issue by mayaCostantini** [AICoE/data-driven-development#61]
**Describe the bug**
Error 404 for the "visualizing metrics" page on https://github.com/AICoE/data-driven-development/tree/main/examples/kebechet 

**To Reproduce**
Go to https://github.com/AICoE/data-driven-development/blob/main/examples/kebechet/visualizing.md at the bottom of the page mentionned above.

**Expected behavior**
Redirects to `visualizing.md`

**Comment by hemajv** [comment]
Yes, we are yet to add this documentation. See https://github.com/AICoE/data-driven-development/issues/39
